### ISSUE TITLE
GitHub wishes

### ISSUE THREAD

**Issue by tieugene** [estraier/tkrzw#14]
This will be good idea to add some GitHub-based things.
E.g. release tarballs with changelog.
I see that 0.9.12 released but don't know what changed and whether to repackage it in Fedora.

**Comment by tieugene** [comment]
And another issue: to show versions compatibility: tkrzw &hArr; tkrzw-python

**Comment by estraier** [comment]
That's a reasonable request.  I'll include ChangeLog from the next version.
And, I'll mention about compatibility with the language interfaces.

In principle, I don't want to break backward compatibility.
However, this time, a symbol (CopyFile) conflicts with a predefined macro from "windows.h".
I cannot help but change the name.
