### ISSUE TITLE
tkrzw does not build from external build directory

### ISSUE THREAD

**Issue by mdorier** [estraier/tkrzw#18]
Right now tkrzw can only be built by calling `configure` from the source directory, which is a bit uncommon. Usually it's preferable to create a build directory somewhere and call configure from there, to not pollute the source tree with build files. e.g. from the source tree:

```
mkdir build
cd build
../configure
make
make install
```
(this will not currently work)

It would be good to be able to build from any directory rather than from within the source tree.

**Comment by estraier** [comment]
I pushed a change to fix this problem.
Makefile now uses VPATH to support building in a subdirectory.
