### ISSUE TITLE
Too hard 'make check' yet

### ISSUE THREAD

**Issue by tieugene** [estraier/tkrzw#23]
'Make check' still produces too high load at building farms and they stop rpm building because of limits:
https://koji.fedoraproject.org/koji/taskinfo?taskID=75900011
Proposition is to split 'make check' into two parts:
1. 'make check' itself that checks functionality correctness (light version)
2. 'make test' (or like this) to run heavy load tests

**Comment by tieugene** [comment]
Another version - this is bug about x32 that was in about 0.9.7, fixed in about 0.9.16 but returns now

**Comment by estraier** [comment]
Hi,
Could you give me logs around the error?

**Comment by estraier** [comment]
I've reproduced the error when I add -m32 to the compiler flags.  I'll
examine it further.

LD_LIBRARY_PATH=.:/usr/local/lib::. ./tkrzw_dbm_perf wicked --dbm hash
--file pos-atom --path casket.tkh \
  --block_size 512  --padding --pagecache \
  --iter 10000 --threads 4 --size 100 --buckets 100000 --iterator --clear
--rebuild --validate
Doing: impl=hash num_iterations=10000 value_size=100 num_threads=4
.................................................. (00000500)
.................................................. (00001000)
.................................................. (00001500)
.................................................. (00002000)
.................................................. (00002500)
.................................................. (00003000)
.................................................. (00003500)
.................................................. (00004000)
.................................................. (00004500)
.................................................. (00005000)
.................................................. (00005500)
.................................................. (00006000)
.................................................. (00006500)
.................................................. (00007000)
.................................................. (00007500)
.................................................. (00008000)
.................................................. (00008500)
.................................................. (00009000)
.................................................. (00009500)
.................................................. (00010000)
Synchronizing: ... done (elapsed=0.000064)
Validating records: ... ValidateRecords failed: BROKEN_DATA_ERROR:
inconsistent effective data size
done (elapsed=0.002479)
Done: elapsed_time=0.373422 num_records=1212 qps=107117 mem=4704000
  file_size=92016 eff_data_size=38654774211 efficiency=42008753.05%
  num_buckets=1447 load_factor=0.84

make[1]: *** [Makefile:291: check-hashdbm-perf] Error 1
make[1]: Leaving directory '/home/mikio/dev/tkrzw'
make: *** [Makefile:143: check] Error 2

**Comment by estraier** [comment]
I fixed the bug and released 1.0.11.

The new Makefile has the "check-light" target which runs essential and lightweight test cases.

**Comment by tieugene** [comment]
I am in testing progress, but as for now another error for ppc64le arch (PowerPC).
- Whole build: https://koji.fedoraproject.org/koji/taskinfo?taskID=75930346
- ppc64le log: https://kojipkgs.fedoraproject.org//work/tasks/448/75930448/build.log
```
...
Get failed: BROKEN_DATA_ERROR: invalid magic checksum
```

**Comment by tieugene** [comment]
It works
