### ISSUE TITLE
Make check fail

### ISSUE THREAD

**Issue by CuriousTim** [estraier/tkrzw#4]
Hello,
I attempted to build tkrzw on my local machine and upon running `make check` (I ran `./configure` and `make` first), I get the following error:
```
...
make check-hashdbm-perf
make[1]: Entering directory '/home/charles/Documents/code/tkrzw'
rm -Rf casket*
LD_LIBRARY_PATH=.:/usr/local/lib:  ./tkrzw_dbm_perf sequence --dbm hash --file mmap-para --path casket.tkh \
  --iter 20000 --threads 5 --size 8 --buckets 100000 --lock_mem_buckets
OpenAdvanced failed: SYSTEM_ERROR: mlock: no enough memory
Setting: impl=hash num_iterations=20000 value_size=8 num_threads=5
Set failed: PRECONDITION_ERROR: not opened database
Set failed: PRECONDITION_ERROR: not opened database
Set failed: Set failed: PRECONDITION_ERROR: not opened database
PRECONDITION_ERROR: not opened database
Set failed: PRECONDITION_ERROR: not opened database
Synchronizing: ... Synchronize failed: PRECONDITION_ERROR: not opened database
done (elapsed=0.000009)
Setting done: elapsed_time=0.000317 num_records=-1 qps=315361203 mem=2596000
  file_size=-1 eff_data_size=-1 efficiency=100.00%
  num_buckets=-1 load_factor=1.00
Close failed: PRECONDITION_ERROR: not opened database

OpenAdvanced failed: BROKEN_DATA_ERROR: bad magic data
Getting: impl=hash num_iterations=20000 value_size=8 num_threads=5
Get failed: PRECONDITION_ERROR: not opened database
Get failed: PRECONDITION_ERROR: not opened database
Get failed: PRECONDITION_ERROR: not opened database
Get failed: PRECONDITION_ERROR: not opened database
Get failed: PRECONDITION_ERROR: not opened database
Getting done: elapsed_time=0.000200 num_records=-1 qps=499917044 mem=2660000
  file_size=-1 eff_data_size=-1 efficiency=100.00%
  num_buckets=-1 load_factor=1.00
Close failed: PRECONDITION_ERROR: not opened database

OpenAdvanced failed: BROKEN_DATA_ERROR: bad magic data
Removing: impl=hash num_iterations=20000 value_size=8 num_threads=5
Remove failed: PRECONDITION_ERROR: not opened database
Remove failed: PRECONDITION_ERROR: not opened database
Remove failed: PRECONDITION_ERROR: not opened database
Remove failed: PRECONDITION_ERROR: not opened database
Remove failed: PRECONDITION_ERROR: not opened database
Synchronizing: ... Synchronize failed: PRECONDITION_ERROR: not opened database
done (elapsed=0.000015)
Removing done: elapsed_time=0.000281 num_records=-1 qps=355750975 mem=2660000
  file_size=-1 eff_data_size=-1 efficiency=100.00%
  num_buckets=-1 load_factor=1.00
Close failed: PRECONDITION_ERROR: not opened database
...
```
Can this error be ignored?

**Comment by CuriousTim** [comment]
My system has 16GB RAM which I figured would be enough. No good?

2020년 12월 18일 (금) 17:58, Mikio Hirabayashi <notifications@github.com>님이 작성:

> it says "no enough memory".
> How much is RAM available on your system?
>
>

**Comment by estraier** [comment]
16GB must be enough as a system.
Then, I guess "ulimit" of the user is not enough.

**Comment by CuriousTim** [comment]
This is my personal machine so I didn't think there would be a user memory limit. I checked `ulimit -v` and I get unlimited. But if this test failing is just due to memory limits, is it possible to limit the memory usage of the library and still use it? I am mostly interested in the on-disk databases.

**Comment by estraier** [comment]
Actually, the failing test is for the memory locking featere, which is not
activated with the file database by default. so, you can ignore the error.

btw, please do
ulimit -l
it shows the limit of memory locking, which causes thw error, I guess.

**Comment by CuriousTim** [comment]
That seems to be it.
```
$ ulimit -l
64
```
with size in KB. Just out of curiosity, would I need to set this limit to the size of the in-memory database to pass the check?

**Comment by estraier** [comment]
The header and the bucket sections only are locked. 100000 is the number of
buckets thus, 4k + 400k is required. So, please set the limit 512k or
something.

**Comment by CuriousTim** [comment]
Awesome, that does the trick. Thank you for your help.

**Comment by estraier** [comment]
Hi,
The error seems to come from the user limit of memory locking.
Please check it by this command.
$ ulimit -l

You can loosen the limit by this, then please run "make check".
$ ulimit -S -l 1024
