### ISSUE TITLE
HashDBM database size and offset_width

### ISSUE THREAD

**Issue by th3r0b0t** [estraier/tkrzw#51]
@estraier Hello sir,
I'd like to offer my sincerest humble appreciation for the awesome work you've done here before anything else.
As I understood, `offset_width` accounts for the addressable space for the records with the formula of `2^(8*W)`; and the block size is determined by `2^P` thus the total size of database is mentioned as number of addressable offsets times the size of the block.  

----  
1. My first question is however, In case we have, say `align_pow=3` and a record with the size of 9-bytes, this record will take up 2 block with padding added as needed; Now if each record is addressed only by it's starting block offset, and each block points to the next block with an offset pointer (which still cannot exceed the addressable space of `2^(8*W)`) the formula holds, but if this is not the case, would you please enlighten me?  
2. In the doc it says: "The offset width affects the size of the buckets and the footprint of each record."; Would you please once again tell me is this affected footprint is only due to the needed bytes to store the offset of each record in the memory and thus the size of the buckets?
3. If `offset_width` limits/specifies the addressable part of the database, are freed blocks also accounted in this space (I mean with `in-place` update mode, will freed block take up space by having an offset)?  

----
I'm sorry I bothered you with a long issue, hope you forgive me.  
Yours.

**Comment by estraier** [comment]
Hi,

Answer to Q1:
If align_pow=3, each record starts at a multiple of 8 (=2^3).  Thus, if a
record starts with 1024, the offset address is represented as 128 (=1024/8).
If offset_width=4, each offset address is between 0 to 2^(4*8).
Therefore, the maximum file size is 2^3 * 2^(4*8) = 32GB.

Answer to Q2:
If the number of buckets is 1000 and offset_width=4, the total size of the
bucket array is 4000.  If offset_width=3, the total size is 3000.

Answer to Q3:
The free block pool uses the same addressing rules.  So, the maximum
address is the same, as in Q1's answer.

**Comment by th3r0b0t** [comment]
Thank you sir; I believe it answers all I had to ask, but if it happens to be the contrast, I'll bother you again.  
I like the issue open until later today.
