### ISSUE TITLE
Out of Bounds access in ProcessCompress 

### ISSUE THREAD

**Issue by SchaichAlonso** [estraier/tkrzw#55]
[AddressSanitizer reports an out of bounds memory access](https://github.com/SchaichAlonso/tkrzw-gha/actions/runs/11406602601/job/31740729810#step:6:1431) in [tkrzw_str_perf.cc:501](https://github.com/estraier/tkrzw/blob/409a57bf7507a4079d0519bc4a023da8ab79e132/tkrzw_str_perf.cc#L501) on github's `ubuntu-latest` agent (requires PR #54 ).

In the triggering line,

    tkrzw::AESCompressor aes_128(std::string("a", 16), 1);

the `std::string("a", 16)` expressions attempts to [copy 16 charactes from the "a" character range](https://cpp-lang.net/docs/std/containers/strings/string/constructors/#copy-character-range-constructor-bound), which is only 2 bytes long (it's `"a\0"`).

It should probably be `std::string(16, 'a')`, [which creates a string of 16 a](https://cpp-lang.net/docs/std/containers/strings/string/constructors/#repeat-character-constructor)'s ("aaaaaaaaaaaaaaaa") instead.

Same goes for string instancations in [line 505](https://github.com/estraier/tkrzw/blob/409a57bf7507a4079d0519bc4a023da8ab79e132/tkrzw_str_perf.cc#L505) and [line 509](https://github.com/estraier/tkrzw/blob/409a57bf7507a4079d0519bc4a023da8ab79e132/tkrzw_str_perf.cc#L509).

**Comment by estraier** [comment]
Nice catch.  Thanks.
I've pushed the fix.

**Comment by SchaichAlonso** [comment]
Thanks.
`make check` can complete on an ubuntu-latest hosted address sanitatized build now.
