### ISSUE TITLE
`--disable-shared` still installs shared library too

### ISSUE THREAD

**Issue by th3r0b0t** [estraier/tkrzw#56]
@estraier Hello again,  
Once more I apologize and thank you for your time and efforts.  
With the configure options of:
```bash
./configure --enable-opt-native --enable-most-features --enable-lz4 --disable-shared --enable-static
```
Shared lib also seems to be installed:
```bash
$~: ls /usr/local/lib/*tk*
/usr/local/lib/libtkrzw.a  /usr/local/lib/libtkrzw.so  /usr/local/lib/libtkrzw.so.1  /usr/local/lib/libtkrzw.so.1.74.0
```
```bash
$~: ldd ./tkrzw_dbm_util
        not a dynamic executable
```
```bash
$~: file /usr/local/lib/libtkrzw.so.1.74.0
/usr/local/lib/libtkrzw.so.1.74.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=23cfef19b2b55ddf218d8e2d5fe71a5dee1a704e, with debug_info, not stripped
```
Is this expected behavior?  
Also wouldn't it be better if using something like `--release` strips the lib and omits debug infos? There's already a `--enable-debug`.  

----
P.S: Best of regards; Humbly yours

**Comment by estraier** [comment]
That's weird.
On my environment, if I run ./configure --disable-shared, Makefile includes the following line.
LIBRARYFILES := libtkrzw.a

This means that only libtkrzw.a is installed under the library directory (/usr/local/lib by default).
Could you check your Makefile?
I guess the library files on your /usr/local/lib might have been put in previous installation attempts.
Could you remove them manually and run the installation process again?

**Comment by th3r0b0t** [comment]
@estraier 
Thank you; Ofc, I'll let you know

**Comment by th3r0b0t** [comment]
@estraier 
Sir, you were right; I installed the library on a fresh system and only the static one has been installed.  
Pardon my disturbance but I'm trying to build a Node.JS binding for the library and thus I bothered you this much; Would you advice me in case of future question would it be more appropriate to open an issue or perhaps contact you by other means like Email?
-----
P.S: Didn't close the issue only bcs of this question of mine.

**Comment by estraier** [comment]
No problem.

As for questions, either is fine.
If the question is informative to other people, please open an issue.
If it is specific only to you, writing e-mails to me is ok.
