### ISSUE TITLE
Is there a way to abort changes?

### ISSUE THREAD

**Issue by GiorgosXou** [estraier/tkrzw#58]
I'm using the C bridge, in combination with HashDBM. Weird question but I was wondering, is there any option I could disable, such that when `dbm` is not closed properly, all changes\set-records get aborted, not written or not restored the next time I re-open it?

**Comment by estraier** [comment]
You can combine the appending mode and tkrzw_dbm_restore_database
<https://dbmx.net/tkrzw/api/tkrzw__langc_8h.html#a203f1ba15a4596455ac8a26f0eabe67c>
function.

If you open the database in the appending mode, each updating operations is
appended at the end of the file.
And, giving the file size as "end_offset" parameter to the function
restores the database of the time when its size is the given one.
Therefore, you can do the following.

1: Open a file which contains the file size of the time when the database
was closed successfully last time.
2: Open the database and get the file size.
3: If the size is different, restore the database and reopen it.
4: Do updating operations.
5: Check the file size.
6: Close the database.
7: Update the file containing the database file size.

**Comment by GiorgosXou** [comment]
Interesting, I'll keep this in mind, thanks!
