### ISSUE TITLE
configure.in: hardcoded special compiler flags

### ISSUE THREAD

**Issue by tieugene** [estraier/tkrzw#7]
As some|many building systems provide they own building plan (verbosity, optimisations, debug info etc) please exclude special flags from defaults.
Like this:
```diff
-MYCFLAGS="-pthread -Wall -ansi -pedantic -fPIC -fsigned-char -g0 -O2"
+MYCFLAGS="-pthread -fPIC -fsigned-char"
-MYCXXFLAGS="-std=c++17 -pthread -Wall -fPIC -fsigned-char -g0 -O2"
+MYCXXFLAGS="-std=c++17 -pthread -fPIC -fsigned-char"
```
I propose to add something like '--enable-opt` into configure options instead of hardcoded.

**Comment by estraier** [comment]
MYCFLAGS and MYCXXFLAGS have been simplified as described above.
You can get the previous behavior by setting "--enable-devel" option.
